### ISSUE TITLE
VNC support

### ISSUE THREAD

**Issue by chibidev** [letiemble/vagrant-tart#19]
Tart supports launching a VM with no GUI but a working VNC server (`--vnc` and `--vnc-experimental`). While disabling GUI is supported in this plugin, it misses the VNC options.

Adding support for these params seems pretty straightforward, so I'd be happy to do it, if you accept PRs and publish a new version when they are merged.

**Comment by letiemble** [comment]
I have merge the support for VNC option. The new Gem has been published.

**Comment by chibidev** [comment]
Awesome, thank you for your hard work!
